version: '3.7' # docker compose语法版本

networks:
  todolist: # 网络
    driver: bridge # 驱动程序

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always # 容器在停止后总是重新启动
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tiktok
      - MYSQL_USER=tiktok
      - MYSQL_PASSWORD=tiktok
      - TZ=Asia/Shanghai
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d/ # 将本地目录 ./config/sql 挂载到容器内部的 /docker-entrypoint-initdb.d/ 目录，提供用于初始化数据库的SQL脚本
    ports:
      - "3306:3306" # 将容器的3306端口映射到主机的3306端口

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - /usr/local/redis:/usr/local/redis # 将主机目录 /usr/local/redis 挂载到容器内部的 /usr/local/redis 目录，可以在主机上持久化存储Redis数据
    ports:
      - "6379:6379"
